// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Katasec.Boundary
{
    /// <summary>
    /// The static host catalog resource allows you to configure a Boundary static-type host catalog. Host catalogs are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host catalog.
    /// </summary>
    [BoundaryResourceType("boundary:index/boundaryHostCatalogStatic:BoundaryHostCatalogStatic")]
    public partial class BoundaryHostCatalogStatic : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The host catalog description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The host catalog name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The scope ID in which the resource is created.
        /// </summary>
        [Output("scopeId")]
        public Output<string> ScopeId { get; private set; } = null!;


        /// <summary>
        /// Create a BoundaryHostCatalogStatic resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BoundaryHostCatalogStatic(string name, BoundaryHostCatalogStaticArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryHostCatalogStatic:BoundaryHostCatalogStatic", name, args ?? new BoundaryHostCatalogStaticArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BoundaryHostCatalogStatic(string name, Input<string> id, BoundaryHostCatalogStaticState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryHostCatalogStatic:BoundaryHostCatalogStatic", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/katasec/pulumi-boundary/releases/downloadv${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BoundaryHostCatalogStatic resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BoundaryHostCatalogStatic Get(string name, Input<string> id, BoundaryHostCatalogStaticState? state = null, CustomResourceOptions? options = null)
        {
            return new BoundaryHostCatalogStatic(name, id, state, options);
        }
    }

    public sealed class BoundaryHostCatalogStaticArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The host catalog description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The host catalog name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope ID in which the resource is created.
        /// </summary>
        [Input("scopeId", required: true)]
        public Input<string> ScopeId { get; set; } = null!;

        public BoundaryHostCatalogStaticArgs()
        {
        }
        public static new BoundaryHostCatalogStaticArgs Empty => new BoundaryHostCatalogStaticArgs();
    }

    public sealed class BoundaryHostCatalogStaticState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The host catalog description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The host catalog name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope ID in which the resource is created.
        /// </summary>
        [Input("scopeId")]
        public Input<string>? ScopeId { get; set; }

        public BoundaryHostCatalogStaticState()
        {
        }
        public static new BoundaryHostCatalogStaticState Empty => new BoundaryHostCatalogStaticState();
    }
}
