// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Katasec.Boundary
{
    /// <summary>
    /// The auth method resource allows you to configure a Boundary auth_method.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Boundary = Katasec.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.BoundaryScope("org", new()
    ///     {
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var password = new Boundary.BoundaryAuthMethod("password", new()
    ///     {
    ///         ScopeId = org.Id,
    ///         Type = "password",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import boundary:index/boundaryAuthMethod:BoundaryAuthMethod foo &lt;my-id&gt;
    /// ```
    /// </summary>
    [BoundaryResourceType("boundary:index/boundaryAuthMethod:BoundaryAuthMethod")]
    public partial class BoundaryAuthMethod : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The auth method description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The minimum login name length.
        /// </summary>
        [Output("minLoginNameLength")]
        public Output<int> MinLoginNameLength { get; private set; } = null!;

        /// <summary>
        /// The minimum password length.
        /// </summary>
        [Output("minPasswordLength")]
        public Output<int> MinPasswordLength { get; private set; } = null!;

        /// <summary>
        /// The auth method name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The scope ID.
        /// </summary>
        [Output("scopeId")]
        public Output<string> ScopeId { get; private set; } = null!;

        /// <summary>
        /// The resource type.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a BoundaryAuthMethod resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BoundaryAuthMethod(string name, BoundaryAuthMethodArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryAuthMethod:BoundaryAuthMethod", name, args ?? new BoundaryAuthMethodArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BoundaryAuthMethod(string name, Input<string> id, BoundaryAuthMethodState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryAuthMethod:BoundaryAuthMethod", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/katasec/pulumi-boundary/releases/downloadv${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BoundaryAuthMethod resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BoundaryAuthMethod Get(string name, Input<string> id, BoundaryAuthMethodState? state = null, CustomResourceOptions? options = null)
        {
            return new BoundaryAuthMethod(name, id, state, options);
        }
    }

    public sealed class BoundaryAuthMethodArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The auth method description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The minimum login name length.
        /// </summary>
        [Input("minLoginNameLength")]
        public Input<int>? MinLoginNameLength { get; set; }

        /// <summary>
        /// The minimum password length.
        /// </summary>
        [Input("minPasswordLength")]
        public Input<int>? MinPasswordLength { get; set; }

        /// <summary>
        /// The auth method name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope ID.
        /// </summary>
        [Input("scopeId", required: true)]
        public Input<string> ScopeId { get; set; } = null!;

        /// <summary>
        /// The resource type.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public BoundaryAuthMethodArgs()
        {
        }
        public static new BoundaryAuthMethodArgs Empty => new BoundaryAuthMethodArgs();
    }

    public sealed class BoundaryAuthMethodState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The auth method description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The minimum login name length.
        /// </summary>
        [Input("minLoginNameLength")]
        public Input<int>? MinLoginNameLength { get; set; }

        /// <summary>
        /// The minimum password length.
        /// </summary>
        [Input("minPasswordLength")]
        public Input<int>? MinPasswordLength { get; set; }

        /// <summary>
        /// The auth method name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope ID.
        /// </summary>
        [Input("scopeId")]
        public Input<string>? ScopeId { get; set; }

        /// <summary>
        /// The resource type.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public BoundaryAuthMethodState()
        {
        }
        public static new BoundaryAuthMethodState Empty => new BoundaryAuthMethodState();
    }
}
