// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Katasec.Boundary
{
    /// <summary>
    /// The static credential store resource allows you to configure a Boundary static credential store.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Boundary = Katasec.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.BoundaryScope("org", new()
    ///     {
    ///         Description = "global scope",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var project = new Boundary.BoundaryScope("project", new()
    ///     {
    ///         Description = "My first scope!",
    ///         ScopeId = org.Id,
    ///         AutoCreateAdminRole = true,
    ///     });
    /// 
    ///     var example = new Boundary.BoundaryCredentialStoreStatic("example", new()
    ///     {
    ///         Description = "My first static credential store!",
    ///         ScopeId = project.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import boundary:index/boundaryCredentialStoreStatic:BoundaryCredentialStoreStatic example_static_credential_store &lt;my-id&gt;
    /// ```
    /// </summary>
    [BoundaryResourceType("boundary:index/boundaryCredentialStoreStatic:BoundaryCredentialStoreStatic")]
    public partial class BoundaryCredentialStoreStatic : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The static credential store description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The static credential store name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The scope for this credential store.
        /// </summary>
        [Output("scopeId")]
        public Output<string> ScopeId { get; private set; } = null!;


        /// <summary>
        /// Create a BoundaryCredentialStoreStatic resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BoundaryCredentialStoreStatic(string name, BoundaryCredentialStoreStaticArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryCredentialStoreStatic:BoundaryCredentialStoreStatic", name, args ?? new BoundaryCredentialStoreStaticArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BoundaryCredentialStoreStatic(string name, Input<string> id, BoundaryCredentialStoreStaticState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryCredentialStoreStatic:BoundaryCredentialStoreStatic", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/katasec/pulumi-boundary/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BoundaryCredentialStoreStatic resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BoundaryCredentialStoreStatic Get(string name, Input<string> id, BoundaryCredentialStoreStaticState? state = null, CustomResourceOptions? options = null)
        {
            return new BoundaryCredentialStoreStatic(name, id, state, options);
        }
    }

    public sealed class BoundaryCredentialStoreStaticArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The static credential store description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The static credential store name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope for this credential store.
        /// </summary>
        [Input("scopeId", required: true)]
        public Input<string> ScopeId { get; set; } = null!;

        public BoundaryCredentialStoreStaticArgs()
        {
        }
        public static new BoundaryCredentialStoreStaticArgs Empty => new BoundaryCredentialStoreStaticArgs();
    }

    public sealed class BoundaryCredentialStoreStaticState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The static credential store description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The static credential store name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The scope for this credential store.
        /// </summary>
        [Input("scopeId")]
        public Input<string>? ScopeId { get; set; }

        public BoundaryCredentialStoreStaticState()
        {
        }
        public static new BoundaryCredentialStoreStaticState Empty => new BoundaryCredentialStoreStaticState();
    }
}
