// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Katasec.Boundary
{
    /// <summary>
    /// The host_set_static resource allows you to configure a Boundary host set. Host sets are always part of a host catalog, so a host catalog resource should be used inline or you should have the host catalog ID in hand to successfully configure a host set.
    /// </summary>
    [BoundaryResourceType("boundary:index/boundaryHostSetStatic:BoundaryHostSetStatic")]
    public partial class BoundaryHostSetStatic : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The host set description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The catalog for the host set.
        /// </summary>
        [Output("hostCatalogId")]
        public Output<string> HostCatalogId { get; private set; } = null!;

        /// <summary>
        /// The list of host IDs contained in this set.
        /// </summary>
        [Output("hostIds")]
        public Output<ImmutableArray<string>> HostIds { get; private set; } = null!;

        /// <summary>
        /// The host set name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The type of host set
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a BoundaryHostSetStatic resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BoundaryHostSetStatic(string name, BoundaryHostSetStaticArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryHostSetStatic:BoundaryHostSetStatic", name, args ?? new BoundaryHostSetStaticArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BoundaryHostSetStatic(string name, Input<string> id, BoundaryHostSetStaticState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/boundaryHostSetStatic:BoundaryHostSetStatic", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/katasec/pulumi-boundary/releases/downloadv${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BoundaryHostSetStatic resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BoundaryHostSetStatic Get(string name, Input<string> id, BoundaryHostSetStaticState? state = null, CustomResourceOptions? options = null)
        {
            return new BoundaryHostSetStatic(name, id, state, options);
        }
    }

    public sealed class BoundaryHostSetStaticArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The host set description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The catalog for the host set.
        /// </summary>
        [Input("hostCatalogId", required: true)]
        public Input<string> HostCatalogId { get; set; } = null!;

        [Input("hostIds")]
        private InputList<string>? _hostIds;

        /// <summary>
        /// The list of host IDs contained in this set.
        /// </summary>
        public InputList<string> HostIds
        {
            get => _hostIds ?? (_hostIds = new InputList<string>());
            set => _hostIds = value;
        }

        /// <summary>
        /// The host set name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of host set
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public BoundaryHostSetStaticArgs()
        {
        }
        public static new BoundaryHostSetStaticArgs Empty => new BoundaryHostSetStaticArgs();
    }

    public sealed class BoundaryHostSetStaticState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The host set description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The catalog for the host set.
        /// </summary>
        [Input("hostCatalogId")]
        public Input<string>? HostCatalogId { get; set; }

        [Input("hostIds")]
        private InputList<string>? _hostIds;

        /// <summary>
        /// The list of host IDs contained in this set.
        /// </summary>
        public InputList<string> HostIds
        {
            get => _hostIds ?? (_hostIds = new InputList<string>());
            set => _hostIds = value;
        }

        /// <summary>
        /// The host set name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of host set
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public BoundaryHostSetStaticState()
        {
        }
        public static new BoundaryHostSetStaticState Empty => new BoundaryHostSetStaticState();
    }
}
