# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .boundary_account import *
from .boundary_account_oidc import *
from .boundary_account_password import *
from .boundary_auth_method import *
from .boundary_auth_method_oidc import *
from .boundary_auth_method_password import *
from .boundary_credential_library_vault import *
from .boundary_credential_ssh_private_key import *
from .boundary_credential_store_static import *
from .boundary_credential_store_vault import *
from .boundary_credential_user_name import *
from .boundary_group import *
from .boundary_host import *
from .boundary_host_catalog import *
from .boundary_host_catalog_plugin import *
from .boundary_host_catalog_static import *
from .boundary_host_set import *
from .boundary_host_set_plugin import *
from .boundary_host_set_static import *
from .boundary_host_static import *
from .boundary_managed_group import *
from .boundary_role import *
from .boundary_scope import *
from .boundary_target import *
from .boundary_user import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import katasec_boundary.config as __config
    config = __config
else:
    config = _utilities.lazy_import('katasec_boundary.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "boundary",
  "mod": "index/boundaryAccount",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAccount:BoundaryAccount": "BoundaryAccount"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryAccountOidc",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAccountOidc:BoundaryAccountOidc": "BoundaryAccountOidc"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryAccountPassword",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAccountPassword:BoundaryAccountPassword": "BoundaryAccountPassword"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryAuthMethod",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAuthMethod:BoundaryAuthMethod": "BoundaryAuthMethod"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryAuthMethodOidc",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAuthMethodOidc:BoundaryAuthMethodOidc": "BoundaryAuthMethodOidc"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryAuthMethodPassword",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryAuthMethodPassword:BoundaryAuthMethodPassword": "BoundaryAuthMethodPassword"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryCredentialLibraryVault",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryCredentialLibraryVault:BoundaryCredentialLibraryVault": "BoundaryCredentialLibraryVault"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryCredentialSshPrivateKey",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryCredentialSshPrivateKey:BoundaryCredentialSshPrivateKey": "BoundaryCredentialSshPrivateKey"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryCredentialStoreStatic",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryCredentialStoreStatic:BoundaryCredentialStoreStatic": "BoundaryCredentialStoreStatic"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryCredentialStoreVault",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryCredentialStoreVault:BoundaryCredentialStoreVault": "BoundaryCredentialStoreVault"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryCredentialUserName",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryCredentialUserName:BoundaryCredentialUserName": "BoundaryCredentialUserName"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryGroup",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryGroup:BoundaryGroup": "BoundaryGroup"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHost",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHost:BoundaryHost": "BoundaryHost"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostCatalog",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostCatalog:BoundaryHostCatalog": "BoundaryHostCatalog"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostCatalogPlugin",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostCatalogPlugin:BoundaryHostCatalogPlugin": "BoundaryHostCatalogPlugin"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostCatalogStatic",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostCatalogStatic:BoundaryHostCatalogStatic": "BoundaryHostCatalogStatic"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostSet",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostSet:BoundaryHostSet": "BoundaryHostSet"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostSetPlugin",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostSetPlugin:BoundaryHostSetPlugin": "BoundaryHostSetPlugin"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostSetStatic",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostSetStatic:BoundaryHostSetStatic": "BoundaryHostSetStatic"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryHostStatic",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryHostStatic:BoundaryHostStatic": "BoundaryHostStatic"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryManagedGroup",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryManagedGroup:BoundaryManagedGroup": "BoundaryManagedGroup"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryRole",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryRole:BoundaryRole": "BoundaryRole"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryScope",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryScope:BoundaryScope": "BoundaryScope"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryTarget",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryTarget:BoundaryTarget": "BoundaryTarget"
  }
 },
 {
  "pkg": "boundary",
  "mod": "index/boundaryUser",
  "fqn": "katasec_boundary",
  "classes": {
   "boundary:index/boundaryUser:BoundaryUser": "BoundaryUser"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "boundary",
  "token": "pulumi:providers:boundary",
  "fqn": "katasec_boundary",
  "class": "Provider"
 }
]
"""
)
