// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The account resource allows you to configure a Boundary account.
type BoundaryAccountOidc struct {
	pulumi.CustomResourceState

	// The resource ID for the auth method.
	AuthMethodId pulumi.StringOutput `pulumi:"authMethodId"`
	// The account description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The OIDC issuer.
	Issuer pulumi.StringPtrOutput `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The OIDC subject.
	Subject pulumi.StringPtrOutput `pulumi:"subject"`
}

// NewBoundaryAccountOidc registers a new resource with the given unique name, arguments, and options.
func NewBoundaryAccountOidc(ctx *pulumi.Context,
	name string, args *BoundaryAccountOidcArgs, opts ...pulumi.ResourceOption) (*BoundaryAccountOidc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AuthMethodId == nil {
		return nil, errors.New("invalid value for required argument 'AuthMethodId'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource BoundaryAccountOidc
	err := ctx.RegisterResource("boundary:index/boundaryAccountOidc:BoundaryAccountOidc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBoundaryAccountOidc gets an existing BoundaryAccountOidc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBoundaryAccountOidc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BoundaryAccountOidcState, opts ...pulumi.ResourceOption) (*BoundaryAccountOidc, error) {
	var resource BoundaryAccountOidc
	err := ctx.ReadResource("boundary:index/boundaryAccountOidc:BoundaryAccountOidc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BoundaryAccountOidc resources.
type boundaryAccountOidcState struct {
	// The resource ID for the auth method.
	AuthMethodId *string `pulumi:"authMethodId"`
	// The account description.
	Description *string `pulumi:"description"`
	// The OIDC issuer.
	Issuer *string `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The OIDC subject.
	Subject *string `pulumi:"subject"`
}

type BoundaryAccountOidcState struct {
	// The resource ID for the auth method.
	AuthMethodId pulumi.StringPtrInput
	// The account description.
	Description pulumi.StringPtrInput
	// The OIDC issuer.
	Issuer pulumi.StringPtrInput
	// The account name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The OIDC subject.
	Subject pulumi.StringPtrInput
}

func (BoundaryAccountOidcState) ElementType() reflect.Type {
	return reflect.TypeOf((*boundaryAccountOidcState)(nil)).Elem()
}

type boundaryAccountOidcArgs struct {
	// The resource ID for the auth method.
	AuthMethodId string `pulumi:"authMethodId"`
	// The account description.
	Description *string `pulumi:"description"`
	// The OIDC issuer.
	Issuer *string `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The OIDC subject.
	Subject *string `pulumi:"subject"`
}

// The set of arguments for constructing a BoundaryAccountOidc resource.
type BoundaryAccountOidcArgs struct {
	// The resource ID for the auth method.
	AuthMethodId pulumi.StringInput
	// The account description.
	Description pulumi.StringPtrInput
	// The OIDC issuer.
	Issuer pulumi.StringPtrInput
	// The account name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The OIDC subject.
	Subject pulumi.StringPtrInput
}

func (BoundaryAccountOidcArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*boundaryAccountOidcArgs)(nil)).Elem()
}

type BoundaryAccountOidcInput interface {
	pulumi.Input

	ToBoundaryAccountOidcOutput() BoundaryAccountOidcOutput
	ToBoundaryAccountOidcOutputWithContext(ctx context.Context) BoundaryAccountOidcOutput
}

func (*BoundaryAccountOidc) ElementType() reflect.Type {
	return reflect.TypeOf((**BoundaryAccountOidc)(nil)).Elem()
}

func (i *BoundaryAccountOidc) ToBoundaryAccountOidcOutput() BoundaryAccountOidcOutput {
	return i.ToBoundaryAccountOidcOutputWithContext(context.Background())
}

func (i *BoundaryAccountOidc) ToBoundaryAccountOidcOutputWithContext(ctx context.Context) BoundaryAccountOidcOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BoundaryAccountOidcOutput)
}

// BoundaryAccountOidcArrayInput is an input type that accepts BoundaryAccountOidcArray and BoundaryAccountOidcArrayOutput values.
// You can construct a concrete instance of `BoundaryAccountOidcArrayInput` via:
//
//	BoundaryAccountOidcArray{ BoundaryAccountOidcArgs{...} }
type BoundaryAccountOidcArrayInput interface {
	pulumi.Input

	ToBoundaryAccountOidcArrayOutput() BoundaryAccountOidcArrayOutput
	ToBoundaryAccountOidcArrayOutputWithContext(context.Context) BoundaryAccountOidcArrayOutput
}

type BoundaryAccountOidcArray []BoundaryAccountOidcInput

func (BoundaryAccountOidcArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BoundaryAccountOidc)(nil)).Elem()
}

func (i BoundaryAccountOidcArray) ToBoundaryAccountOidcArrayOutput() BoundaryAccountOidcArrayOutput {
	return i.ToBoundaryAccountOidcArrayOutputWithContext(context.Background())
}

func (i BoundaryAccountOidcArray) ToBoundaryAccountOidcArrayOutputWithContext(ctx context.Context) BoundaryAccountOidcArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BoundaryAccountOidcArrayOutput)
}

// BoundaryAccountOidcMapInput is an input type that accepts BoundaryAccountOidcMap and BoundaryAccountOidcMapOutput values.
// You can construct a concrete instance of `BoundaryAccountOidcMapInput` via:
//
//	BoundaryAccountOidcMap{ "key": BoundaryAccountOidcArgs{...} }
type BoundaryAccountOidcMapInput interface {
	pulumi.Input

	ToBoundaryAccountOidcMapOutput() BoundaryAccountOidcMapOutput
	ToBoundaryAccountOidcMapOutputWithContext(context.Context) BoundaryAccountOidcMapOutput
}

type BoundaryAccountOidcMap map[string]BoundaryAccountOidcInput

func (BoundaryAccountOidcMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BoundaryAccountOidc)(nil)).Elem()
}

func (i BoundaryAccountOidcMap) ToBoundaryAccountOidcMapOutput() BoundaryAccountOidcMapOutput {
	return i.ToBoundaryAccountOidcMapOutputWithContext(context.Background())
}

func (i BoundaryAccountOidcMap) ToBoundaryAccountOidcMapOutputWithContext(ctx context.Context) BoundaryAccountOidcMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BoundaryAccountOidcMapOutput)
}

type BoundaryAccountOidcOutput struct{ *pulumi.OutputState }

func (BoundaryAccountOidcOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BoundaryAccountOidc)(nil)).Elem()
}

func (o BoundaryAccountOidcOutput) ToBoundaryAccountOidcOutput() BoundaryAccountOidcOutput {
	return o
}

func (o BoundaryAccountOidcOutput) ToBoundaryAccountOidcOutputWithContext(ctx context.Context) BoundaryAccountOidcOutput {
	return o
}

// The resource ID for the auth method.
func (o BoundaryAccountOidcOutput) AuthMethodId() pulumi.StringOutput {
	return o.ApplyT(func(v *BoundaryAccountOidc) pulumi.StringOutput { return v.AuthMethodId }).(pulumi.StringOutput)
}

// The account description.
func (o BoundaryAccountOidcOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BoundaryAccountOidc) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The OIDC issuer.
func (o BoundaryAccountOidcOutput) Issuer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BoundaryAccountOidc) pulumi.StringPtrOutput { return v.Issuer }).(pulumi.StringPtrOutput)
}

// The account name. Defaults to the resource name.
func (o BoundaryAccountOidcOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *BoundaryAccountOidc) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The OIDC subject.
func (o BoundaryAccountOidcOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BoundaryAccountOidc) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

type BoundaryAccountOidcArrayOutput struct{ *pulumi.OutputState }

func (BoundaryAccountOidcArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BoundaryAccountOidc)(nil)).Elem()
}

func (o BoundaryAccountOidcArrayOutput) ToBoundaryAccountOidcArrayOutput() BoundaryAccountOidcArrayOutput {
	return o
}

func (o BoundaryAccountOidcArrayOutput) ToBoundaryAccountOidcArrayOutputWithContext(ctx context.Context) BoundaryAccountOidcArrayOutput {
	return o
}

func (o BoundaryAccountOidcArrayOutput) Index(i pulumi.IntInput) BoundaryAccountOidcOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *BoundaryAccountOidc {
		return vs[0].([]*BoundaryAccountOidc)[vs[1].(int)]
	}).(BoundaryAccountOidcOutput)
}

type BoundaryAccountOidcMapOutput struct{ *pulumi.OutputState }

func (BoundaryAccountOidcMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BoundaryAccountOidc)(nil)).Elem()
}

func (o BoundaryAccountOidcMapOutput) ToBoundaryAccountOidcMapOutput() BoundaryAccountOidcMapOutput {
	return o
}

func (o BoundaryAccountOidcMapOutput) ToBoundaryAccountOidcMapOutputWithContext(ctx context.Context) BoundaryAccountOidcMapOutput {
	return o
}

func (o BoundaryAccountOidcMapOutput) MapIndex(k pulumi.StringInput) BoundaryAccountOidcOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *BoundaryAccountOidc {
		return vs[0].(map[string]*BoundaryAccountOidc)[vs[1].(string)]
	}).(BoundaryAccountOidcOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BoundaryAccountOidcInput)(nil)).Elem(), &BoundaryAccountOidc{})
	pulumi.RegisterInputType(reflect.TypeOf((*BoundaryAccountOidcArrayInput)(nil)).Elem(), BoundaryAccountOidcArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*BoundaryAccountOidcMapInput)(nil)).Elem(), BoundaryAccountOidcMap{})
	pulumi.RegisterOutputType(BoundaryAccountOidcOutput{})
	pulumi.RegisterOutputType(BoundaryAccountOidcArrayOutput{})
	pulumi.RegisterOutputType(BoundaryAccountOidcMapOutput{})
}
