// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The account resource allows you to configure a Boundary account.
 */
export class BoundaryAccountOidc extends pulumi.CustomResource {
    /**
     * Get an existing BoundaryAccountOidc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BoundaryAccountOidcState, opts?: pulumi.CustomResourceOptions): BoundaryAccountOidc {
        return new BoundaryAccountOidc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'boundary:index/boundaryAccountOidc:BoundaryAccountOidc';

    /**
     * Returns true if the given object is an instance of BoundaryAccountOidc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BoundaryAccountOidc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BoundaryAccountOidc.__pulumiType;
    }

    /**
     * The resource ID for the auth method.
     */
    public readonly authMethodId!: pulumi.Output<string>;
    /**
     * The account description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The OIDC issuer.
     */
    public readonly issuer!: pulumi.Output<string | undefined>;
    /**
     * The account name. Defaults to the resource name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The OIDC subject.
     */
    public readonly subject!: pulumi.Output<string | undefined>;

    /**
     * Create a BoundaryAccountOidc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BoundaryAccountOidcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BoundaryAccountOidcArgs | BoundaryAccountOidcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BoundaryAccountOidcState | undefined;
            resourceInputs["authMethodId"] = state ? state.authMethodId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["issuer"] = state ? state.issuer : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["subject"] = state ? state.subject : undefined;
        } else {
            const args = argsOrState as BoundaryAccountOidcArgs | undefined;
            if ((!args || args.authMethodId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'authMethodId'");
            }
            resourceInputs["authMethodId"] = args ? args.authMethodId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["issuer"] = args ? args.issuer : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["subject"] = args ? args.subject : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BoundaryAccountOidc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BoundaryAccountOidc resources.
 */
export interface BoundaryAccountOidcState {
    /**
     * The resource ID for the auth method.
     */
    authMethodId?: pulumi.Input<string>;
    /**
     * The account description.
     */
    description?: pulumi.Input<string>;
    /**
     * The OIDC issuer.
     */
    issuer?: pulumi.Input<string>;
    /**
     * The account name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The OIDC subject.
     */
    subject?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BoundaryAccountOidc resource.
 */
export interface BoundaryAccountOidcArgs {
    /**
     * The resource ID for the auth method.
     */
    authMethodId: pulumi.Input<string>;
    /**
     * The account description.
     */
    description?: pulumi.Input<string>;
    /**
     * The OIDC issuer.
     */
    issuer?: pulumi.Input<string>;
    /**
     * The account name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The OIDC subject.
     */
    subject?: pulumi.Input<string>;
}
