// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The target resource allows you to configure a Boundary target.
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import boundary:index/boundaryTarget:BoundaryTarget foo <my-id>
 * ```
 */
export class BoundaryTarget extends pulumi.CustomResource {
    /**
     * Get an existing BoundaryTarget resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BoundaryTargetState, opts?: pulumi.CustomResourceOptions): BoundaryTarget {
        return new BoundaryTarget(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'boundary:index/boundaryTarget:BoundaryTarget';

    /**
     * Returns true if the given object is an instance of BoundaryTarget.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BoundaryTarget {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BoundaryTarget.__pulumiType;
    }

    /**
     * A list of brokered credential source ID's.
     */
    public readonly brokeredCredentialSourceIds!: pulumi.Output<string[] | undefined>;
    /**
     * The default port for this target.
     */
    public readonly defaultPort!: pulumi.Output<number | undefined>;
    /**
     * The target description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * A list of host source ID's.
     */
    public readonly hostSourceIds!: pulumi.Output<string[] | undefined>;
    /**
     * A list of injected application credential source ID's.
     */
    public readonly injectedApplicationCredentialSourceIds!: pulumi.Output<string[] | undefined>;
    /**
     * The target name. Defaults to the resource name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The scope ID in which the resource is created. Defaults to the provider's `defaultScope` if unset.
     */
    public readonly scopeId!: pulumi.Output<string>;
    public readonly sessionConnectionLimit!: pulumi.Output<number>;
    public readonly sessionMaxSeconds!: pulumi.Output<number>;
    /**
     * The target resource type.
     */
    public readonly type!: pulumi.Output<string>;
    /**
     * Boolean expression to filter the workers for this target
     */
    public readonly workerFilter!: pulumi.Output<string | undefined>;

    /**
     * Create a BoundaryTarget resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BoundaryTargetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BoundaryTargetArgs | BoundaryTargetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BoundaryTargetState | undefined;
            resourceInputs["brokeredCredentialSourceIds"] = state ? state.brokeredCredentialSourceIds : undefined;
            resourceInputs["defaultPort"] = state ? state.defaultPort : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["hostSourceIds"] = state ? state.hostSourceIds : undefined;
            resourceInputs["injectedApplicationCredentialSourceIds"] = state ? state.injectedApplicationCredentialSourceIds : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["scopeId"] = state ? state.scopeId : undefined;
            resourceInputs["sessionConnectionLimit"] = state ? state.sessionConnectionLimit : undefined;
            resourceInputs["sessionMaxSeconds"] = state ? state.sessionMaxSeconds : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["workerFilter"] = state ? state.workerFilter : undefined;
        } else {
            const args = argsOrState as BoundaryTargetArgs | undefined;
            if ((!args || args.scopeId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'scopeId'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["brokeredCredentialSourceIds"] = args ? args.brokeredCredentialSourceIds : undefined;
            resourceInputs["defaultPort"] = args ? args.defaultPort : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["hostSourceIds"] = args ? args.hostSourceIds : undefined;
            resourceInputs["injectedApplicationCredentialSourceIds"] = args ? args.injectedApplicationCredentialSourceIds : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["scopeId"] = args ? args.scopeId : undefined;
            resourceInputs["sessionConnectionLimit"] = args ? args.sessionConnectionLimit : undefined;
            resourceInputs["sessionMaxSeconds"] = args ? args.sessionMaxSeconds : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["workerFilter"] = args ? args.workerFilter : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BoundaryTarget.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BoundaryTarget resources.
 */
export interface BoundaryTargetState {
    /**
     * A list of brokered credential source ID's.
     */
    brokeredCredentialSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The default port for this target.
     */
    defaultPort?: pulumi.Input<number>;
    /**
     * The target description.
     */
    description?: pulumi.Input<string>;
    /**
     * A list of host source ID's.
     */
    hostSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A list of injected application credential source ID's.
     */
    injectedApplicationCredentialSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The target name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The scope ID in which the resource is created. Defaults to the provider's `defaultScope` if unset.
     */
    scopeId?: pulumi.Input<string>;
    sessionConnectionLimit?: pulumi.Input<number>;
    sessionMaxSeconds?: pulumi.Input<number>;
    /**
     * The target resource type.
     */
    type?: pulumi.Input<string>;
    /**
     * Boolean expression to filter the workers for this target
     */
    workerFilter?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BoundaryTarget resource.
 */
export interface BoundaryTargetArgs {
    /**
     * A list of brokered credential source ID's.
     */
    brokeredCredentialSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The default port for this target.
     */
    defaultPort?: pulumi.Input<number>;
    /**
     * The target description.
     */
    description?: pulumi.Input<string>;
    /**
     * A list of host source ID's.
     */
    hostSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A list of injected application credential source ID's.
     */
    injectedApplicationCredentialSourceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The target name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The scope ID in which the resource is created. Defaults to the provider's `defaultScope` if unset.
     */
    scopeId: pulumi.Input<string>;
    sessionConnectionLimit?: pulumi.Input<number>;
    sessionMaxSeconds?: pulumi.Input<number>;
    /**
     * The target resource type.
     */
    type: pulumi.Input<string>;
    /**
     * Boolean expression to filter the workers for this target
     */
    workerFilter?: pulumi.Input<string>;
}
