// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Deprecated: use `boundary.BoundaryHostCatalogStatic` instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as boundary from "@katasec/boundary";
 *
 * const org = new boundary.BoundaryScope("org", {
 *     description: "My first scope!",
 *     scopeId: boundary_scope.global.id,
 *     autoCreateAdminRole: true,
 *     autoCreateDefaultRole: true,
 * });
 * const project = new boundary.BoundaryScope("project", {
 *     description: "My first scope!",
 *     scopeId: org.id,
 *     autoCreateAdminRole: true,
 * });
 * const example = new boundary.BoundaryHostCatalog("example", {
 *     description: "My first host catalog!",
 *     type: "Static",
 *     scopeId: project.id,
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import boundary:index/boundaryHostCatalog:BoundaryHostCatalog foo <my-id>
 * ```
 */
export class BoundaryHostCatalog extends pulumi.CustomResource {
    /**
     * Get an existing BoundaryHostCatalog resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BoundaryHostCatalogState, opts?: pulumi.CustomResourceOptions): BoundaryHostCatalog {
        return new BoundaryHostCatalog(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'boundary:index/boundaryHostCatalog:BoundaryHostCatalog';

    /**
     * Returns true if the given object is an instance of BoundaryHostCatalog.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BoundaryHostCatalog {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BoundaryHostCatalog.__pulumiType;
    }

    /**
     * The host catalog description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The host catalog name. Defaults to the resource name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The scope ID in which the resource is created.
     */
    public readonly scopeId!: pulumi.Output<string>;
    /**
     * The host catalog type. Only `static` is supported.
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a BoundaryHostCatalog resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BoundaryHostCatalogArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BoundaryHostCatalogArgs | BoundaryHostCatalogState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BoundaryHostCatalogState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["scopeId"] = state ? state.scopeId : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as BoundaryHostCatalogArgs | undefined;
            if ((!args || args.scopeId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'scopeId'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["scopeId"] = args ? args.scopeId : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BoundaryHostCatalog.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BoundaryHostCatalog resources.
 */
export interface BoundaryHostCatalogState {
    /**
     * The host catalog description.
     */
    description?: pulumi.Input<string>;
    /**
     * The host catalog name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The scope ID in which the resource is created.
     */
    scopeId?: pulumi.Input<string>;
    /**
     * The host catalog type. Only `static` is supported.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BoundaryHostCatalog resource.
 */
export interface BoundaryHostCatalogArgs {
    /**
     * The host catalog description.
     */
    description?: pulumi.Input<string>;
    /**
     * The host catalog name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The scope ID in which the resource is created.
     */
    scopeId: pulumi.Input<string>;
    /**
     * The host catalog type. Only `static` is supported.
     */
    type: pulumi.Input<string>;
}
