// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The static host resource allows you to configure a Boundary static host. Hosts are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host.
 */
export class BoundaryHostStatic extends pulumi.CustomResource {
    /**
     * Get an existing BoundaryHostStatic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BoundaryHostStaticState, opts?: pulumi.CustomResourceOptions): BoundaryHostStatic {
        return new BoundaryHostStatic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'boundary:index/boundaryHostStatic:BoundaryHostStatic';

    /**
     * Returns true if the given object is an instance of BoundaryHostStatic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BoundaryHostStatic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BoundaryHostStatic.__pulumiType;
    }

    /**
     * The static address of the host resource as `<IP>` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
     */
    public readonly address!: pulumi.Output<string | undefined>;
    /**
     * The host description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly hostCatalogId!: pulumi.Output<string>;
    /**
     * The host name. Defaults to the resource name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The type of host
     */
    public readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a BoundaryHostStatic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BoundaryHostStaticArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BoundaryHostStaticArgs | BoundaryHostStaticState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BoundaryHostStaticState | undefined;
            resourceInputs["address"] = state ? state.address : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["hostCatalogId"] = state ? state.hostCatalogId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as BoundaryHostStaticArgs | undefined;
            if ((!args || args.hostCatalogId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hostCatalogId'");
            }
            resourceInputs["address"] = args ? args.address : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["hostCatalogId"] = args ? args.hostCatalogId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BoundaryHostStatic.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BoundaryHostStatic resources.
 */
export interface BoundaryHostStaticState {
    /**
     * The static address of the host resource as `<IP>` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
     */
    address?: pulumi.Input<string>;
    /**
     * The host description.
     */
    description?: pulumi.Input<string>;
    hostCatalogId?: pulumi.Input<string>;
    /**
     * The host name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The type of host
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BoundaryHostStatic resource.
 */
export interface BoundaryHostStaticArgs {
    /**
     * The static address of the host resource as `<IP>` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
     */
    address?: pulumi.Input<string>;
    /**
     * The host description.
     */
    description?: pulumi.Input<string>;
    hostCatalogId: pulumi.Input<string>;
    /**
     * The host name. Defaults to the resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The type of host
     */
    type?: pulumi.Input<string>;
}
